### PR TITLE
Replaced deprecated functions

### PR DESCRIPTION
**Pull request by rprimmer**
Hi Shakeeb, 

FWIW, this version updates the two deprecated function. 

See Changes.md for description.

Thanks,
Rob

### CODE REVIEW

**Comment by shakfu** [comment]
Hi @rprimmer thanks for the PR

Incidentally, I recently committed a change to get rid of the deprecated function. I'm not so familiar with this Apple api, how does my change compared to yours?

**Comment by rprimmer** [comment]
Too funny -- I hadn't thought to recheck your code to see if it had changed.

Your code looks great. It does use the `CFRunLoopRun()` function, which I believe is deprecated, but apparently still works. For that I had just replaced that call with an infinite loop `while(true)` but I think we both went with the new function `FSEventStreamScheduleWithRunLoop()`

**Comment by shakfu** [comment]
@rprimmer 

It looks like we had the same idea and both version seem to work ok :smile:

**Comment by rprimmer** [comment]
Sounds good. You can just go ahead and reject the PR as it's no longer applicable.

**Comment by shakfu** [comment]
@rprimmer 

> It does use the `CFRunLoopRun()` function, which I believe is deprecated, but apparently still works.

I just check it the online docs for [CFRunLoopRun](https://developer.apple.com/documentation/corefoundation/1542011-cfrunlooprun), it doesn't look like it's deprecated.

**Pull request closed without merging**
